### PR TITLE
fix(cthuang): Redirect user to signup or user profile page after sign in

### LINKED ISSUE #89: [Bug] User not redirected after authentication
**Describe the bug**
After user go through the Oauth flow to sign in, they got the token but not redirected back to the user profile page.
image

**To Reproduce**
1. Go to https://staging.devlaunchers.org/
2. Click Sign In

**Expected behavior**
User is redirected to the staging website.

**Additional context**[
@dbradham noticed https://github.com/dev-launchers/strapi/blob/main/extensions/users-permissions/controllers/Auth.js#L219-L225 is not migrated to v4.

### PR DESCRIPTION
**Pull request by chungthuang**
fixes #89

### CODE REVIEW

**Review by dbradham — COMMENTED** [review]
Looks good to me but I was getting some strange behavior testing this locally which is different than what I've seen on staging... I was able to select my google account as expected, and then a request was sent to my strapi local's relative path at: `/api/connect/google/api/auth/google/callback?id_token=ey` instead of `/api/auth/...` so the conditional to set the cookie wasn't even executing. Likely related to something in my local config.

**Review by dbradham — APPROVED** [review]

**Comment by chungthuang** [comment]
> Looks good to me but I was getting some strange behavior testing this locally which is different than what I've seen on staging... I was able to select my google account as expected, and then a request was sent to my strapi local's relative path at: `/api/connect/google/api/auth/google/callback?id_token=ey` instead of `/api/auth/...` so the conditional to set the cookie wasn't even executing. Likely related to something in my local config.

In http://localhost:1337/admin/settings/users-permissions/providers, what is `The redirect URL to your front-end app`? I put `http://localhost:1337/api/auth/google/callback` and pass the actual frontend URL in the `redirectURL` query parameter, so the request looks like http://localhost:1337/api/connect/google?redirectURL=http://localhost:3000/users/me

File: src/extensions/users-permissions/server/middlewares/jwt.js [hunk 1]
```diff
@@ -32,6 +32,21 @@ module.exports = (options, { strapi }) => {
             sameSite: 'None'
           });
         }
+
+        const grant = ctx.session.grant;
```
Comment (chungthuang) [inline src/extensions/users-permissions/server/middlewares/jwt.js:36]: @dapowers87 any suggestion to make this easier to read?
