### PR TITLE
fix(chungthuang): fineOne project needs to read slug from ctx.request…

### LINKED ISSUE #105: [Bug] Get project endpoint returns 500
**Describe the bug**
Get project endpoint returns 500 because it's slug incorrectly

**To Reproduce**
1. Run strapi locally
2. GET /api/projects/:slug
3. Receive 500

**Expected behavior**
Return the project or 404

### PR DESCRIPTION
**Pull request by chungthuang**
….params.id

Closes #105

### CODE REVIEW

File: src/api/project/controllers/project.js [hunk 1]
```diff
@@ -4,82 +4,29 @@ const { createCoreController } = require('@strapi/strapi').factories;
...
-          id: member.member.id,
-          username: member.member.username,
-          profile: member.member.profile,
-          role: member.role,
-        }));
-        return entity;
-    },
-
-    
-/*
```
Comment (chungthuang) [inline src/api/project/controllers/project.js:31]: Removed unused code.

File: src/api/project/controllers/project.js [hunk 2]
```diff
@@ -4,82 +4,29 @@ const { createCoreController } = require('@strapi/strapi').factories;
 
 module.exports = createCoreController('api::project.project', ({ strapi }) => ({
     async findOne(ctx) {
-        const { slug } = ctx.params;
+        const slug = ctx.request.params.id;
```
Comment (chungthuang) [inline src/api/project/controllers/project.js:7]: This was the fix. See https://docs.strapi.io/dev-docs/backend-customization/requests-responses#ctxrequest.

File: src/api/project/controllers/project.js [hunk 3]
```diff
@@ -4,82 +4,29 @@ const { createCoreController } = require('@strapi/strapi').factories;
...
-           
-            for(const interest of interests){
-                for(const category of interest.categories){
-                    getProjectSlugs(projects, category);
-                }
-            }
-            console.log("Last for loop")
-            
-            // Using the project slugs, I get the project and add them to the recommendedProjects array
+        if (entity?.team) {
```
Comment (chungthuang) [inline src/api/project/controllers/project.js:13]: This makes sure we return 404 if entity is not found.
